language: python
python:
  - "3.8"

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - docker-compose up -d

script:
  - sudo docker exec antifragile_web pytest tests/tests.py

after_script:
  - docker-compose down