version: '3.4'
services:
  web:
    build: .

    ports:
    - 5000:5000
    command: ["python", "main.py"]
    volumes:
      - ./services:/app

    depends_on:
      - database

  database:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: antifragile_user
      POSTGRES_PASSWORD: antifragile_password
      POSTGRES_DB: antifragile
      PGDATA: /var/lib/postgresql/data
    networks:
      - default
    restart: always
